### ISSUE TITLE
Can you please upload dataset of  indian Financial news, if you do that would be of great help

### ISSUE THREAD

**Issue by mahimdashora** [kritika-srivastava/The-Sparks-Foundation-Tasks#2]

**Comment by kritika-srivastava** [comment]
@mahimdashora I have uploaded the dataset for News Headlines in csv/india-news-headlines.csv using git lfs as the file size was very large (~228 MB).
To be able to access the files smoothly, please run the following two commands on git bash or the respective environment.

`
git lfs install
`
`
git lfs track "*.csv"
`
`
git lfs fetch  
`
OR
`
git lfs pull
`
[Whichever works for you]
For more information, check the article here - https://towardsdatascience.com/uploading-large-files-to-github-dbef518fa1a

Please let me know if this helps. Following this I will close this issue.

**Comment by mahimdashora** [comment]
Thanks I got the dataset
